{{- if .Values.grafanaAgent.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hivebox.fullname" . }}-grafana-agent-remote-write
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-agent
type: Opaque
stringData:
  PROM_REMOTE_WRITE_URL: {{ .Values.grafanaAgent.remoteWrite.prometheus.url | quote }}
  PROM_REMOTE_WRITE_USERNAME: {{ .Values.grafanaAgent.remoteWrite.prometheus.username | quote }}
  PROM_REMOTE_WRITE_PASSWORD: {{ .Values.grafanaAgent.remoteWrite.prometheus.password | quote }}
  LOKI_PUSH_URL: {{ .Values.grafanaAgent.remoteWrite.loki.url | quote }}
  LOKI_USERNAME: {{ .Values.grafanaAgent.remoteWrite.loki.username | quote }}
  LOKI_PASSWORD: {{ .Values.grafanaAgent.remoteWrite.loki.password | quote }}
{{- end }}
