{{- if .Values.grafanaAgent.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hivebox.fullname" . }}-grafana-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
