{{- if .Values.grafanaAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hivebox.fullname" . }}-grafana-agent
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-agent
{{- end }}
