apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hivebox.fullname" . }}-minio-credentials
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.minio.accessKey | quote }}
  secretKey: {{ .Values.minio.secretKey | quote }}
