apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hivebox.fullname" . }}-minio-config
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
data:
  bucket: {{ .Values.minio.bucket | quote }}
  secure: {{ .Values.minio.secure | quote }}
  createBucket: {{ .Values.minio.createBucket | quote }}
