{{- if .Values.valkey.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    {{- include "hivebox.labels" . | nindent 4 }}
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - name: client
      port: 6379
      targetPort: 6379
      protocol: TCP
{{- end }}
