@baseUrl = http://localhost:5000

### Version
GET {{baseUrl}}/version

### Temperature
GET {{baseUrl}}/temperature

### Store (flush to MinIO)
POST {{baseUrl}}/store

### Metrics
GET {{baseUrl}}/metrics
