apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-remote-write
  labels:
    app: grafana-agent
type: Opaque
stringData:
  PROM_REMOTE_WRITE_URL: https://prometheus-prod-<region>.grafana.net/api/prom/push
  PROM_REMOTE_WRITE_USERNAME: <prometheus-instance-id>
  PROM_REMOTE_WRITE_PASSWORD: <grafana-cloud-metrics-write-token>
  LOKI_PUSH_URL: https://logs-prod-<region>.grafana.net/loki/api/v1/push
  LOKI_USERNAME: <loki-instance-id>
  LOKI_PASSWORD: <grafana-cloud-logs-write-token>
