apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hivebox-network-policy
spec:
  podSelector:
    matchLabels:
      app: hivebox
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - ports:
        - protocol: TCP
          port: 443
    - to:
        - podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
    - ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
